# Generated by Django 4.1.7 on 2024-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
