# Generated by Django 4.1.7 on 2024-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(max_length=2080, upload_to=''),
        ),
    ]
